import type { PartialBlock } from "@blocknote/core";

export interface BuiltInTemplate {
  id: string;
  name: string;
  description: string;
  category: "Starter" | "Meeting Notes" | "Project" | "Personal" | "Database";
  icon: string;
  blocks: PartialBlock[];
}

const h = (text: string, level: 1 | 2 | 3 = 2): PartialBlock => ({
  type: "heading",
  props: { level },
  content: text,
});
const p = (text = ""): PartialBlock => ({ type: "paragraph", content: text });
const li = (text: string): PartialBlock => ({ type: "bulletListItem", content: text });
const todo = (text: string): PartialBlock => ({ type: "checkListItem", content: text });

export const BUILT_IN_TEMPLATES: BuiltInTemplate[] = [
  {
    id: "prd-sid-v1",
    name: "PRD — SID Template v1.0",
    description:
      "Product Requirements Document standar SID. 20 section: Problem Statement, User Stories (Connextra), Acceptance Criteria (Gherkin), RBAC matrix, Risk table, Edge Cases, Success Metrics, Timeline.",
    category: "Project",
    icon: "📋",
    blocks: [
      h("Feature / Product Name", 1),
      p("👆 Ganti dengan nama fitur. Hapus baris panduan ini sebelum submit."),
      p(),

      h("0. Document Metadata"),
      li("Product Name: [Feature Name]"),
      li("Status: DRAFT"),
      li("ClickUp Project/Epic: TBD — [PM] — [date]"),
      li("Version: 1.0"),
      li("Lead PM: [name]"),
      li("Tech Lead: TBD — [name] — [date]"),
      li("Designer: TBD — [name] — [date]"),
      li("QA Lead: TBD — [name] — [date]"),
      li("Created: " + new Date().toISOString().slice(0, 10)),
      p(),

      h("1. Change Log"),
      li(new Date().toISOString().slice(0, 10) + " | v1.0 | Initial draft | [PM]"),
      p(),

      h("2. Executive Summary"),
      p("Apa yang dibangun? Untuk siapa? Kenapa sekarang? Apa yang berubah setelah live? (Max 200 kata. Bayangkan dibaca CEO dalam 30 detik.)"),
      p(),

      h("3. Problem Statement"),
      h("3.1 Background", 3),
      p("Konteks bisnis & teknis sebelum problem ini muncul. 1-2 paragraf."),
      h("3.2 Problem Definition", 3),
      p("[User segment] saat ini [mengalami friksi spesifik] ketika [konteks/trigger], yang menyebabkan [konsekuensi terukur]."),
      h("3.3 Evidence", 3),
      li("Support ticket: TBD — [PM] — [date]"),
      li("NPS / survey: TBD"),
      li("Analytics / drop-off: TBD"),
      h("3.4 Impact & Urgency (Why Now)", 3),
      p("Kenapa harus dikerjakan sekarang? Quantify cost of inaction per bulan/quarter."),
      p(),

      h("4. Target Users"),
      h("4.1 Primary Users", 3),
      p("**[Role spesifik]** — konteks, frekuensi pakai, platform (web/mobile), technical literacy."),
      h("4.2 Secondary Users", 3),
      p("Stakeholder yang terpengaruh secara tidak langsung."),
      h("4.3 Non-Users (Out of Persona)", 3),
      p("Siapa yang TIDAK dilayani di iterasi ini. Eksplisit — mencegah scope creep."),
      p(),

      h("5. Goals & Success Metrics"),
      h("5.1 Business Goals", 3),
      li("Goal 1"),
      li("Goal 2"),
      h("5.2 User Goals", 3),
      li("Goal 1"),
      h("5.3 North Star Metric", 3),
      p("[Metric name] [naik/turun] dari [baseline] ke [target] dalam [timeframe]. Contoh: 'Time to publish turun dari 45 menit ke 15 menit dalam 60 hari.'"),
      h("5.4 Leading Indicators", 3),
      li("Indicator 1 — metric yang bergerak lebih cepat dari North Star"),
      li("Indicator 2"),
      h("5.5 Guardrail Metrics", 3),
      li("Crash rate ≤ 0.5%"),
      li("Support ticket tidak naik > 20%"),
      h("5.6 Success Criteria (Go/No-Go)", 3),
      p("Definisi konkret sukses dalam X minggu setelah launch."),
      p(),

      h("6. Solution Overview"),
      h("6.1 Solution Approach", 3),
      p("High-level approach. 2-3 paragraf. Bukan field-by-field detail."),
      h("6.2 Key Design Principles", 3),
      li("Prinsip 1 — contoh: Tidak boleh require user learn new mental model"),
      li("Prinsip 2 — contoh: Semua destructive action butuh konfirmasi"),
      h("6.3 Why This Approach (vs Alternatives)", 3),
      p("Alternatif yang dipertimbangkan dan kenapa approach ini dipilih."),
      p(),

      h("7. Scope"),
      h("7.1 In Scope (P1 — This Release)", 3),
      li("Fitur/capability yang DIKERJAKAN"),
      h("7.2 Out of Scope", 3),
      li("Yang TIDAK dikerjakan — eksplisit untuk cegah scope creep"),
      h("7.3 Future Considerations (P2, P3)", 3),
      li("Untuk iterasi berikutnya — documented tapi tidak committed"),
      p(),

      h("8. User Stories & Acceptance Criteria"),
      h("8.1 User Stories (Connextra format)", 3),
      li("US-01 [P1]: As a [role spesifik], I want to [action], so that [outcome]."),
      li("US-02 [P1]: As a [role spesifik], I want to [action], so that [outcome]."),
      li("US-03 [P2]: As a [role spesifik], I want to [action], so that [outcome]."),
      p("⚠️ Min 3 user stories. Role harus spesifik (Core Admin, Academic Lead, Peserta) — bukan 'user' generik."),
      h("8.2 Acceptance Criteria (Gherkin format)", 3),
      p("US-01: [Story title]"),
      li("AC-01.1: Given [context], When [action], Then [expected result]"),
      li("AC-01.2: Given [context], When [action], Then [expected result]"),
      p("US-02: [Story title]"),
      li("AC-02.1: Given [context], When [action], Then [expected result]"),
      p("⚠️ AC harus testable — bisa dijadikan test case otomatis tanpa interpretasi."),
      h("8.3 User Journey", 3),
      p("Flow dari trigger sampai outcome. Gunakan Embed (tombol di toolbar) untuk embed Miro/Figma/diagram."),
      p(),

      h("9. Functional Requirements"),
      h("9.1 Core Capabilities", 3),
      li("Capability tingkat tinggi — field-level detail masuk DFS terpisah"),
      h("9.2 Non-Functional Requirements", 3),
      li("Performance: Page load < 2s di 3G network"),
      li("Scalability: Support [X] concurrent users"),
      li("Security: RBAC sesuai Section 10"),
      li("Accessibility: WCAG 2.1 AA"),
      li("Localization: Bahasa Indonesia + English"),
      h("9.3 Detail Implementation Spec (DFS)", 3),
      p("DFS terpisah dibuat post-PRD-approval. Link: TBD — [PM] — [date]"),
      p(),

      h("10. Roles & Permissions (RBAC)"),
      h("10.1 Role Matrix", 3),
      li("Super Admin: Create ✅ | Read ✅ | Update ✅ | Delete ✅ | Approve ✅ | Publish ✅"),
      li("Academic Lead: Create ✅ | Read ✅ | Update ✅ | Delete ❌ | Approve ✅ | Publish ✅"),
      li("Instruktur: Create ❌ | Read ✅ | Update ❌ | Delete ❌ | Approve ❌ | Publish ❌"),
      li("Core Admin: [isi sesuai fitur]"),
      li("Peserta: Create ❌ | Read ✅ (own only) | Update ❌ | Delete ❌ | Approve ❌ | Publish ❌"),
      h("10.2 Sensitive Actions", 3),
      li("Action yang butuh audit log, extra confirmation, atau approval workflow"),
      p(),

      h("11. Dependencies"),
      h("11.1 Cross-Tribe Dependencies", 3),
      li("[Tribe] | [Dependency] | Owner: TBD — [name] — [date] | Status: Pending"),
      h("11.2 External Dependencies", 3),
      li("Third-party services atau vendor contracts"),
      h("11.3 Internal System Dependencies", 3),
      li("Internal services: notification, audit log, feature flag, dll"),
      p(),

      h("12. Stakeholders (RACI)"),
      li("Lead PM — R (Responsible)"),
      li("Tech Lead — A (Accountable — 1 orang max)"),
      li("Designer — C (Consulted)"),
      li("QA Lead — C (Consulted)"),
      li("Business Owner — I (Informed)"),
      p(),

      h("13. Risk Management"),
      p("⚠️ Min 5 risks. Mitigation harus actionable — bukan 'monitor closely'."),
      li("R-01 | [Risk] | Likelihood: Med | Impact: High | Mitigation: [actionable] | Owner: TBD"),
      li("R-02 | [Risk] | Likelihood: Low | Impact: Med | Mitigation: [actionable] | Owner: TBD"),
      li("R-03 | [Risk] | | | |"),
      li("R-04 | [Risk] | | | |"),
      li("R-05 | [Risk] | | | |"),
      p(),

      h("14. Edge Cases"),
      p("⚠️ Min 5 edge cases (10+ untuk fitur complex)."),
      li("EC-01 | Empty state (no data) | [expected behavior]"),
      li("EC-02 | API timeout / error | [expected behavior]"),
      li("EC-03 | Concurrent edit / race condition | [expected behavior]"),
      li("EC-04 | Permission revoked mid-session | [expected behavior]"),
      li("EC-05 | Invalid input format | [expected behavior]"),
      p(),

      h("15. Testability & Observability"),
      h("15.1 Test Strategy", 3),
      li("Unit test: 80%+ coverage pada business logic"),
      li("Integration test: API endpoints + DB operations"),
      li("E2E: Critical user journeys (happy path + top 3 error paths)"),
      li("Manual QA: [scope]"),
      h("15.2 Feature Flag Plan", 3),
      li("Flag name: [feature_name]_enabled"),
      li("Rollout: 0% → 10% internal → 50% beta → 100% GA"),
      li("Kill switch: if error rate > 1% OR ticket spike > 50%"),
      h("15.3 Observability", 3),
      li("Business metrics: [dashboard panels yang dibutuhkan]"),
      li("Technical metrics: latency, error rate, throughput"),
      h("15.4 Validation Plan", 3),
      p("Post-launch review T+7 dan T+30. A/B test design jika applicable."),
      p(),

      h("16. Tech Feasibility"),
      h("16.1 Proposed Stack & Approach", 3),
      p("High-level architectural approach. Detail di tech design doc terpisah."),
      h("16.2 Effort Estimate", 3),
      li("Design: [X sprint] | Confidence: Med"),
      li("Development: [X sprint] | Confidence: Med"),
      li("QA: [X sprint] | Confidence: Med"),
      li("Total: [X sprint] | Confidence: Med"),
      h("16.3 Technical Risks", 3),
      li("Linked ke Section 13: [R-XX] — [tech-specific risk]"),
      h("16.4 Migration & Rollback Plan", 3),
      p("Data migration yang dibutuhkan? Rollback strategy jika ada issue?"),
      p(),

      h("17. Timeline & Milestones"),
      li("PRD Approved | TBD — PM | Document signed off | PM"),
      li("Design Approved | TBD — Designer | Figma final | Designer"),
      li("Tech Design Approved | TBD — Tech Lead | Tech doc | Tech Lead"),
      li("Sprint 1 Start | TBD | [scope] | Tech Lead"),
      li("Internal Beta | TBD | Behind feature flag | Tech Lead"),
      li("Public Beta | TBD | 10% rollout | PM"),
      li("GA | TBD | 100% rollout | PM"),
      li("Post-Launch Review T+30 | TBD | Metrics vs Section 5 | PM"),
      p(),

      h("18. Open Questions"),
      p("⚠️ Setiap question WAJIB ada owner + deadline. Tanpa itu → pindah ke Assumptions."),
      li("Q-01 | [Question blocking development] | Owner: TBD — [name] — [date] | Deadline: [date]"),
      li("Q-02 | [Non-blocking question] | Owner: TBD — [name] — [date] | Deadline: [date]"),
      p(),

      h("19. Assumptions"),
      li("A-01: [Assumption — jika salah, PRD perlu di-revisit]"),
      li("A-02: [Assumption]"),
      p(),

      h("20. References"),
      li("Figma: TBD — [link]"),
      li("User Research: TBD — [link]"),
      li("Related PRDs: TBD — [links]"),
      li("ClickUp Epic: TBD — [link]"),
      li("DFS: akan dibuat post-PRD-approval"),
      li("Tech Design Doc: TBD"),
      p(),
      p("---"),
      p("Generated using SID PRD Template v1.0 | SobatPM score target: 80+/100 | Run scoring di PRD Builder → Sobat PM"),
    ],
  },
  {
    id: "meeting-notes",
    name: "Meeting Notes",
    description: "Agenda, attendees, action items, and notes",
    category: "Meeting Notes",
    icon: "📝",
    blocks: [
      h("Agenda"),
      li("Topic 1"),
      li("Topic 2"),
      h("Attendees"),
      li("Name"),
      h("Action items"),
      todo("First action item"),
      h("Notes"),
      p(),
    ],
  },
  {
    id: "project-brief",
    name: "Project Brief",
    description: "Overview, goals, timeline, team, resources",
    category: "Project",
    icon: "🎯",
    blocks: [
      h("Overview"),
      p(),
      h("Goals"),
      li("Goal 1"),
      h("Timeline"),
      p(),
      h("Team"),
      p(),
      h("Resources"),
      p(),
    ],
  },
  {
    id: "weekly-review",
    name: "Weekly Review",
    description: "Reflect on the week and plan ahead",
    category: "Personal",
    icon: "📅",
    blocks: [
      h("What went well"),
      li(""),
      h("What to improve"),
      li(""),
      h("Next week focus"),
      todo(""),
    ],
  },
  {
    id: "bug-report",
    name: "Bug Report",
    description: "Summary, steps, expected, actual, screenshots",
    category: "Project",
    icon: "🐛",
    blocks: [
      h("Summary"),
      p(),
      h("Steps to reproduce"),
      { type: "numberedListItem", content: "Step 1" },
      h("Expected"),
      p(),
      h("Actual"),
      p(),
      h("Screenshots"),
      p(),
    ],
  },
  {
    id: "personal-journal",
    name: "Personal Journal",
    description: "Mood, highlights, gratitude, tomorrow",
    category: "Personal",
    icon: "📔",
    blocks: [
      h("Mood"),
      p(),
      h("Today's highlights"),
      li(""),
      h("Gratitude"),
      li(""),
      h("Tomorrow's plan"),
      todo(""),
    ],
  },
  {
    id: "okr-tracker",
    name: "OKR Tracker",
    description: "Objective and key results",
    category: "Starter",
    icon: "🎯",
    blocks: [
      h("Objective", 1),
      p("What do you want to achieve?"),
      h("Key Results"),
      todo("Key result 1 — measurable"),
      todo("Key result 2 — measurable"),
      todo("Key result 3 — measurable"),
    ],
  },
  {
    id: "reading-list",
    name: "Reading List",
    description: "Books and articles to read",
    category: "Personal",
    icon: "📚",
    blocks: [
      h("Reading List", 1),
      p("Track what you want to read."),
      h("Currently reading"),
      li("Book title — Author"),
      h("Up next"),
      li(""),
      h("Finished"),
      li(""),
    ],
  },
  {
    id: "content-calendar",
    name: "Content Calendar",
    description: "Plan content across channels",
    category: "Starter",
    icon: "🗓️",
    blocks: [
      h("Content Calendar", 1),
      h("This week"),
      todo("Mon — Channel — Title"),
      todo("Wed — Channel — Title"),
      todo("Fri — Channel — Title"),
      h("Backlog"),
      li(""),
    ],
  },
];
