import { NextRequest, NextResponse } from "next/server";
import { generate } from "@/lib/gemini";
import { prisma } from "@/lib/prisma";

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const prd = await prisma.pRD.findUnique({ where: { id } });
    if (!prd) return NextResponse.json({ error: "PRD not found" }, { status: 404 });

    const system = `Kamu adalah expert PRD writer untuk SID/Sekolah.mu — platform pendidikan terbesar di Indonesia.
Tugasmu adalah menghasilkan PRD (Product Requirements Document) yang komprehensif, terstruktur, dan siap dipresentasikan ke stakeholder.

Format output harus dalam Markdown dengan struktur berikut:

# [JUDUL PRD]

## 1. Executive Summary
Ringkasan 2-3 paragraf tentang produk/fitur ini.

## 2. Problem Statement
### 2.1 Background
### 2.2 Problem Definition
### 2.3 Impact & Urgency

## 3. Target Users
### 3.1 Primary Users
### 3.2 User Personas
### 3.3 User Journey Map (singkat)

## 4. Goals & Success Metrics
### 4.1 Business Goals
### 4.2 User Goals
### 4.3 Key Performance Indicators (KPIs)
### 4.4 Success Criteria

## 5. Solution Overview
### 5.1 Solution Approach
### 5.2 High-Level Features
### 5.3 Why This Solution

## 6. Scope
### 6.1 In Scope
### 6.2 Out of Scope
### 6.3 Future Considerations

## 7. Requirements
### 7.1 Functional Requirements
### 7.2 Non-Functional Requirements
### 7.3 Technical Requirements

## 8. Dependencies & Risks
### 8.1 Dependencies
### 8.2 Risks & Mitigations
### 8.3 Assumptions

## 9. Timeline & Milestones
(Draft estimasi berdasarkan scope)

## 10. Stakeholders
(Identifikasi stakeholder yang relevan)

## 11. Open Questions
(Pertanyaan yang masih perlu dijawab)

---
*Generated by Sobat PM | SID/Sekolah.mu*`;

    const userContent = `Buat PRD berdasarkan brief berikut:

**Judul:** ${prd.title}
**Problem:** ${prd.problem || "Belum diisi"}
**Target User:** ${prd.targetUser || "Belum diisi"}
**Why Now:** ${prd.whyNow || "Belum diisi"}
**Desired Outcome:** ${prd.desiredOutcome || "Belum diisi"}
**Evidence:** ${prd.evidence || "Belum diisi"}
**In Scope:** ${prd.inScope.length > 0 ? prd.inScope.map((s) => `- ${s}`).join("\n") : "Belum diisi"}
**Out of Scope:** ${prd.outOfScope.length > 0 ? prd.outOfScope.map((s) => `- ${s}`).join("\n") : "Belum diisi"}
**Dependencies:** ${prd.dependencies || "Belum diisi"}
**Risks:** ${prd.risks || "Belum diisi"}
${prd.gdriveUrl ? `**Context dari Google Drive:** ${prd.gdriveTitle || prd.gdriveUrl}` : ""}

Buat PRD yang komprehensif. Gunakan bahasa Indonesia yang profesional. Lengkapi dengan inferensi yang masuk akal berdasarkan konteks SID/Sekolah.mu jika ada field yang belum terisi.`;

    const generatedPRD = await generate(system, userContent, 4096);

    const updatedPrd = await prisma.pRD.update({
      where: { id },
      data: {
        generatedPRD,
        status: "GENERATED",
        currentStep: "DRAFT_PRD",
      },
    });

    return NextResponse.json(updatedPrd);
  } catch (error) {
    console.error("POST /api/prd/[id]/generate error:", error);
    return NextResponse.json({ error: "Failed to generate PRD" }, { status: 500 });
  }
}
